# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0427c6247bc964e71bbbf3b92cdeff510375a19ae89d04d6bbcf33f42e747316cc1ee4c8079fcfe6723aedae41a0a03279a41b4f3e5bdc54cc824db15714050b

test:
  secret_key_base: 7720ef7cbbd7bc5145e4cd56d7c4a6feceecbd4c33608877b38f04be8b96761f9d24ff859fdd9a25bc2893ee3bef55bdbccf6be275c8a28c91ac49d1a1cbec55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
